project:
  type: website
  output-dir: docs

website:
  title: "Ls 빅데이터 스쿨 4기 - 남원정 qmd 블로그"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://wonjeongnam.github.io/wonjeong-blog/
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css



